const STATES = {
	TT : {
		name : "All States & UT",
		helpline : "",
		state_code : "TT",
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	AN : {
		name : "Andaman and Nicobar Islands",
		helpline : "+91-3192-232102",
		state_code : "AN",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	AP : {
		name : "Andhra Pradesh",
		helpline : "+91-866-2410978",
		state_code : "AP",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	AR : {
		name : "Arunachal Pradesh",
		helpline : "+91-9436055743",
		state_code : "AR",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	AS : {
		name : "Assam",
		helpline : "+91-6913347770",
		state_code : "AS",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	BR : {
		name : "Bihar",
		helpline : "104",
		state_code : "BR",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	CH : {
		name : "Chandigarh",
		helpline : "+91-9779558282",
		state_code : "CH",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	CT : {
		name : "Chhattisgarh",
		helpline : "104",
		state_code : "CT",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	DD : {
		name : "Daman & Diu",
		helpline : "104",
		state_code : "DD",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	DL : {
		name : "Delhi",
		helpline : "+91-11-22307145",
		state_code : "DL",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	DN : {
		name : "Dadra and Nagar Haveli",
		helpline : "104",
		state_code : "DN",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	GA : {
		name : "Goa",
		helpline : "104",
		state_code : "GA",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	GJ : {
		name : "Gujarat",
		helpline : "104",
		state_code : "GJ",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	HP : {
		name : "Himachal Pradesh",
		helpline : "104",
		state_code : "HP",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	HR : {
		name : "Haryana",
		helpline : "+91-8558893911",
		state_code : "HR",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	JH : {
		name : "Jharkhand",
		helpline : "104",
		state_code : "JH",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	JK : {
		name : "Jammu and Kashmir",
		helpline : "+91-191-2520982, +91-194-2440283",
		state_code : "JK",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	KA : {
		name : "Karnataka",
		helpline : "104",
		state_code : "KA",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	KL : {
		name : "Kerala",
		helpline : "+91-471-2552056",
		state_code : "KL",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	LA : {
		name : "Ladakh",
		helpline : "+91-1982-256462",
		state_code : "LA",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	LD : {
		name : "Lakshadweep",
		helpline : "104",
		state_code : "LD",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	MH : {
		name : "Maharashtra",
		helpline : "+91-20-26127394",
		state_code : "MH",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	ML : {
		name : "Meghalaya",
		helpline : "108",
		state_code : "ML",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	MN : {
		name : "Manipur",
		helpline : "+91-3852411668",
		state_code : "MN",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	MP : {
		name : "Madhya Pradesh",
		helpline : "+91-755-2527177",
		state_code : "MP",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	MZ : {
		name : "Mizoram",
		helpline : "102",
		state_code : "MZ",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	NL : {
		name : "Nagaland",
		helpline : "+91-7005539653",
		state_code : "NL",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	OR : {
		name : "Odisha",
		helpline : "+91-9439994859",
		state_code : "OR",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	PB : {
		name : "Punjab",
		helpline : "104",
		state_code : "PB",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	PY : {
		name : "Puducherry",
		helpline : "104",
		state_code : "PY",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	RJ : {
		name : "Rajasthan",
		helpline : "+91-141-2225624",
		state_code : "RJ",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	SK : {
		name : "Sikkim",
		helpline : "104",
		state_code : "SK",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	TG : {
		name : "Telangana",
		helpline : "104",
		state_code : "TG",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	TN : {
		name : "Tamil Nadu",
		helpline : "+91-44-29510500",
		state_code : "TN",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	TR : {
		name : "Tripura",
		helpline : "+91-381-2315879",
		state_code : "TR",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	UP : {
		name : "Uttar Pradesh",
		helpline : "18001805145",
		state_code : "UP",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	UT : {
		name : "Uttarakhand",
		helpline : "104",
		state_code : "UT",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	},
	WB : {
		name : "West Bengal",
		helpline : "1800313444222, +91-3323412600",
		state_code : "WB",
		districts : {},
		confirmed : {},
		deceased : {},
		recovered : {},
		tested : {},
		vaccinated : {},
		latest : undefined
	}
};

export default STATES;